repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: go-fmt
        name: go-fmt
        entry: gofmt -s -w
        language: system
        types: [go]
        description: Format Go code

      - id: go-imports
        name: go-imports
        entry: goimports -w -local github.com/isdmx/watchdog
        language: system
        types: [go]
        description: Format Go imports

      - id: go-vet
        name: go-vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false
        description: Vet Go code for common errors

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        types: [go]
        pass_filenames: false
        description: Lint Go code

      - id: go-test
        name: go-test
        entry: go test ./...
        language: system
        types: [go]
        pass_filenames: false
        description: Run Go tests

      - id: go-build
        name: go-build
        entry: go build ./cmd/watchdog
        language: system
        types: [go]
        pass_filenames: false
        description: Build the server to ensure code compiles
